objects/Sighting__c.object
<CustomObject>
    <description>The recorded sighting of a species in time and space.</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date at which the sighting was done.</description>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Location_Precision__c</fullName>
        <description>Precision of the Sighting Location coordinates.</description>
        <label>Location Precision</label>
        <picklist>
            <picklistValues>
                <fullName>10 meters</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>100 meters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1000 meters</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Animals__c</fullName>
        <label>Number of Animals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Species_Group__c</fullName>
        <label>Species Group</label>
        <picklist>
            <picklistValues>
                <fullName>Mammals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fungi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arachnids</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Butterflies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dragonflies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diptera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hymenoptera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other invertebrates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birds</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Species__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Species</label>
        <referenceTo>Species__c</referenceTo>
        <relationshipLabel>Sightings</relationshipLabel>
        <relationshipName>Sightings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validation_Status__c</fullName>
        <description>Validation Status of the Sighting, should default to &apos;Not Validated&apos;.</description>
        <label>Validation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Validated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Validation Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sighting</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Sighting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sightings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Species__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Species_Group__c</fullName>
        <description>The group of the specie in which Biosightings separates species for reporting and analytics.</description>
        <label>Species Group</label>
        <picklist>
            <picklistValues>
                <fullName>Mammals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fungi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arachnids</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Butterflies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dragonflies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diptera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hymenoptera</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other invertebrates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Birds</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Species</label>
    <nameField>
        <label>Species Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Species</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Sightings_Validated__c</fullName>
        <description>Amount of sightings that have been validated by the user if he has a Validation Specialization.</description>
        <label>Sightings Validated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/BatchUserValidationsCountTest.cls
@isTest
private class BatchUserValidationsCountTest {
   
    @testSetup static void userSetup() {
        // Create users and species
        List<Profile> userProfiles = [SELECT Id FROM Profile WHERE Name = 'Data Validator'];
        List<UserRole> roles = [SELECT Id FROM UserRole WHERE Name = 'BioSightings Member'];
        
        
        List<String> speciesGroups = new List<String> {'Mammals', 'Fish', 'Plants'};
        
        // Create some users
        List<User> users = new List<User>();
        for (Integer index = 0; index < 2; index++) {
            User user = new User(Alias = 'userd'+index, Email='user2d@testuser.org', 
                EmailEncodingKey='UTF-8', LastName='Tester', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = userProfiles[0].Id, UserRoleId = roles[0].Id,
                TimeZoneSidKey='America/Los_Angeles', UserName='batchtest'+index+'userguy@testorg.com', 
                Default_Sighting_Location__Latitude__s = 30, Default_Sighting_Location__Longitude__s = -140);
            users.add(user);
        }
        insert users;
    }
    @isTest static void testBatchProcess() {
        
        List<User> users = [Select Id, Sightings_Validated__c from User where Email = 'user2d@testuser.org'];
        
        // Create some species
        List<Species__c> species = new List<Species__c>();
        List<String> speciesGroups = new List<String> {'Mammals', 'Fish', 'Plants'};
        for (Integer index = 0; index < 3; index++) {          
            Species__c specie = new Species__c(Name = 'Species'+index, External_Id__c = index+'species', Species_Group__c = speciesGroups[math.mod(index, 3)]);
            species.add(specie);
        }
        insert species;
        
        // Create some sightings
        List<Sighting__c> sightings = new List<Sighting__c>();
        for (Integer index = 1; index < 101; index++) {
            Sighting__c sighting = new Sighting__c();
            sighting.Date__c = date.today().addDays(-Integer.valueOf(10 * Math.random()));
            sighting.Location_Precision__c = '10 meters';
            sighting.Location__Latitude__s = index/50;
            sighting.Location__Longitude__s = -180;
            sighting.Number_of_Animals__c = index;
            sighting.OwnerId = users[0].Id;
            sighting.Species__c = species[math.mod(index, 2)].id;
            sighting.Validation_Status__c = 'Not Validated';
            sightings.add(sighting);
        }
        insert sightings;
        
        System.runAs(users[0]) {
            for (Integer x = 0; x < 25; x++) {
                sightings[x].Validation_Status__c = 'Approved';
            }
            update sightings;
        }       
        
        Test.startTest();
        
        BatchUserValidationsCount validationCount = new BatchUserValidationsCount();
        ID batchprocessid = Database.executeBatch(validationCount);
        Test.stopTest();
        System.assertEquals(25, [Select Sightings_Validated__c from User where Id =:users[0].Id].Sightings_Validated__c);
        System.assertEquals(null, [Select Sightings_Validated__c from User where Id =:users[1].Id].Sightings_Validated__c);
    }
}