objects/Sighting__c.object
<CustomObject>
    <description>The recorded sighting of a species in time and space.</description>
    <fields>
        <fullName>Validated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the Species Group Expert who validated the record. May be blank if the record was validated automatically.</description>
        <label>Validated By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ValidatedSightings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Validation_Status__c</fullName>
        <description>Validation Status of the Sighting, should default to &apos;Not Validated&apos;.</description>
        <label>Validation Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Validated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Validation Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Sighting</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Sighting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sightings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Sightings_Validated__c</fullName>
        <description>Amount of sightings that have been validated by the user if he has a Validation Specialization.</description>
        <label>Sightings Validated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/BatchUserValidationsCount.cls
global class BatchUserValidationsCount implements Database.Batchable<AggregateResult> {

    private String query;
    private String validationStatus = 'Approved';
    
    global BatchUserValidationsCount() {
        
        query = 'Select Validated_By__c, Count(Id) FROM Sighting__c  where Validation_Status__c = :validationStatus'+
            ' group by Validated_By__c';
    }
    
    global Iterable<AggregateResult> start(Database.BatchableContext bc) {
        return new AggregateResultIterable(query, validationStatus);
    }
    
    global void execute(Database.BatchableContext bc, List<sObject> scope) {
        List<String> userIds = new List<String>();
        Map<String, Integer> userValidations = new Map<String, Integer>();
        for(sObject sObj : scope) {
            AggregateResult ar = (AggregateResult)sObj;
            userIds.add(String.valueOf(ar.get('Validated_By__c')));
            userValidations.put(String.valueOf(ar.get('Validated_By__c')), Integer.valueOf(ar.get('expr0')));
        }

        // Get the user object and then update its Sightings_Validated__c
        Map<Id, User> usersMap = new Map<Id, User>([SELECT Id, Sightings_Validated__c from User where Id IN:userIds]);
        for (String userId : userValidations.keyset()) {
            usersMap.get(userId).Sightings_Validated__c = userValidations.get(userId);
        }
        update usersMap.values();
    }

    global void finish(Database.BatchableContext bc) { 
    }
}